routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => "HomeController@index"])->name('index');
Route::get('/posts/{slug}', ['uses' => "PostController@show"])->name('posts.show');
Route::get('/page/{slug}', ['uses' => 'PageController@show'])->name('pages.show');
Route::get('/search/{q?}', ['uses' => 'HomeController@search'])->name('search');
Route::post('/subscribe', ['uses' => 'HomeController@subscribe'])->name('subscribe');
Route::get('/category/{slug}', ['uses' => 'CategoryController@index'])->name('category');
Route::get('/contact-us', ['uses' => 'ContactController@show'])->name('contact');
Route::post('/contact-us', ['uses' => 'ContactController@send'])->name('contact-us');
Route::get('/regenerate_media/{offset?}', 'MediaRegeneratController@regenerate_media')->name('media.cron');

app/Models/Page.php
<?php

namespace App\Models;

use Dot\Pages\Models\Page as Model;

class Page extends Model
{
    /**
     * Path attribute
     * @return string
     */
    public function getPathAttribute()
    {
        return route('pages.show', ['slug' => $this->slug]);
    }
}

resources/views/category.blade.php
@extends('layouts.app')
@section('title',$category->name)
@section('content')
    <style>
        .video-wrapper iframe {
            position: relative;
        }
    </style>
    <section class="category">
        @include('layouts.partials.header')
        <div class="container">
            <!--<img src="img/ball.png" alt="" class="ball">-->
            <div class="sliderContainer clearfix">
                <!--<img src="img/red.png" alt="" class="red-video">
                <img src="img/green.png" alt="" class="green-video">-->
                <!--<img src="img/lines.png" alt="" class="lines-video">-->
                <div class="swiper-container gallery-top col-12" dir="rtl">
                    <div class="swiper-wrapper">
                        @php $i = 0; @endphp
                        @foreach($videos as $video)
                            <div class="swiper-slide">
                                <div class="video-wrapper">
                                    <div id="rv-{{$i}}" class="video-card">
                                        <div class="video text-center">
                                            <video poster="{{thumbnail($video->image->path, 'video-details')}}"
                                                   class="video" data-id="{{$i}}" src="{{$video->media->path}}">
                                            </video>
                                        </div>
                                        <button id="{{$i}}" class="play-card"><i  class="icon-play"></i></button>
                                    </div>
                                </div>
                            </div>
                            @php $i++; @endphp
                        @endforeach
                    </div>
                </div>
                <div class="below-video">
                    <div>
                        <img src="{{thumbnail($category->image->path, 'category-logo-cat')}}" alt=""
                             class="ball-icon">
                        <span class="third-title-font">{{$category->name}}</span>
                    </div>
                    <div class="position-relative">
                        <div class="swiper-container gallery-thumbs" dir="rtl">
                            <div class="swiper-wrapper">
                                @foreach($videos as $video)
                                    <div class="swiper-slide">
                                        <img src="{{thumbnail($video->image->path,'swiper-small')}}" alt="">
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <!-- Add Arrows -->
                        <div class="swiper-button-next swiper-button-white">
                            <i id="stop" class="icon-slider-right"></i>
                        </div>
                        <div class="swiper-button-prev swiper-button-white">
                            <i id="stop" class="icon-slider-left"></i>
                        </div>
                    </div>
                    <div class="total-videos">
                    <span>
                        {{category_count($category->id)}}.
                    </span>
                        فيديو
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="padding-section category-videos">
        <div class="container">
            <div class="cards">
                @include('extensions.index-videos', $videos)
                @if(count($videos) == 12)
                    <div class="btn-more">
                        <button class="more">{{trans('app.more')}}</button>
                    </div>
                @endif
            </div>
        </div>
    </section>
    @include('extensions.subscribe')
@endsection
@push('scripts')
    <script src="https://www.youtube.com/iframe_api"></script>
    <script>
        $(function () {
            offset = 12
            $('.btn-more').on('click', function () {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: "get",
                    url: "{{route('category',['slug' => $category->slug])}}",
                    data: {'offset': offset, 'limit': 12},
                    success: function (data) {
                        if (data.count > 0) {
                            $(data.view).insertBefore('.btn-more');
                            offset += data.count;
                            $('.card').each(function () {
                                if ($(this).isInViewport()) {
                                    $(this).css({
                                        opacity: '1',
                                        transform: 'translateY(-10px)'
                                    });
                                }
                            });
                        }
                        if (data.count < 12)
                            $('.btn-more').remove();
                    }
                })
            });

            v = 0;
            videos = [];
            function initVideos(id){
                for(i = 0; i < 2; ++i){
                    var video = $('#rv-'+i).find('video')[0];
                    var src = video.src;
                    var poster = video.poster;
                    var div = $('#rv-' + i);
                    var height = div.height();
                    var width = div.width();
                    var vid = src.split('embed/')[1];
                    videos[i] = new YT.Player('rv-'+i, {
                        height: height,
                        width: width,
                        videoId: vid,
                        playerVars: {'autoplay': 0, 'controls': 1},
                        /*events: {
                            onStateChange: function (e) {
                                if (e.data == 0)
                                    alert()
                                    stopVideo(i, poster, src)
                            }
                        }*/
                    })
                }

                videos[id].playVideo()
            }
            $(document).on('click', '.play-card', function (e) {
                //initVideos($(this).attr('id'));
                //return;
                e.preventDefault()
                var video = $(this).closest('.video-card').find('video');
                var src = video[0].src;
                var poster = video[0].poster;
                var div = $('#rv-' + video[0].dataset.id);
                var height = div.height();
                var width = div.width();
                var id = video[0].dataset.id;
                var vid = src.split('embed/')[1];
                videos[v] = new YT.Player('rv-' + id, {
                    width: width,
                    height: height,
                    videoId: vid,
                    playerVars: {'autoplay': 1, 'controls': 1},
                    autoplay: 1,
                    events: {
                        onStateChange: function (e) {
                            if (e.data == 0)
                                stopVideo(id, poster, src)
                        }
                    }
                });
                v++;
            });

            function stopVideo(id, poster, src) {
                $('#rv-' + id).hide();
                $("<div id=\"rv-" + id + "\" class=\"video-card\">\n" +
                    "                                        <div  class=\"video text-center\">\n" +
                    "                                            <video poster=\"" + poster + "\"\n" +
                    "                                                   class=\"video\" data-id=\"" + id + "\" src=\"" + src + "\">\n" +
                    "                                            </video>\n" +
                    "                                        </div>\n" +
                    "                                        <button class=\"play-card\"><i class=\"icon-play\"></i></button>\n" +
                    "                                    </div>").insertBefore('#rv-' + id);
                $('iframe#rv-'+id).remove();
            }
        })
    </script>

@endpush

resources/views/contact-us.blade.php
@extends('layouts.app')
@section('title',trans('app.contact_us'))
@section('content')
    <section class="contact">
        @include('layouts.partials.header')
        <div class="container">
            <p class="third-title-font padding-section pb-45">{{trans('app.contact_us')}}</p>
            <p style="display: none" class="third-title-font confirm">شكراً للتواصل معنا</p>
            <div class="contact-section to-hide clearfix">
                <form class="d-inline-block" id="contact-form">
                    <div class="frist-input d-inline-block">
                        <input name="first_name" type="text" placeholder="{{trans('app.first_name')}}" maxlength="50"
                               min-characters="3"
                               max-characters="50">
                        <p style="display: none" id="error_first_name">{{trans('app.error_first_name')}}</p>
                    </div>
                    <div class="frist-input d-inline-block">
                        <input name="last_name" type="text" placeholder="{{trans('app.last_name')}}" maxlength="50"
                               min-characters="3"
                               max-characters="50">
                        <p style="display: none" id="error_last_name">{{trans('app.error_last_name')}}</p>
                    </div>
                    <div class="frist-input d-inline-block phone">
                        <input name="number" type="number" placeholder="{{trans('app.number')}}" maxlength="11"
                               min-characters="11"
                               max-characters="11">
                        <p style="display: none" id="error_number">{{trans('app.error_number')}}</p>
                    </div>
                    <div class="frist-input d-inline-block">
                        <input name="email" type="text" placeholder="{{trans('app.email')}}" maxlength="50"
                               min-characters="6"
                               max-characters="50">
                        <p style="display: none" id="error_email">{{trans('app.error_email')}}</p>
                    </div>
                    <div class="frist-input message">
                        <textarea name="message" placeholder="{{trans('app.message')}}" maxlength="500"
                                  min-characters="3"
                                  max-characters="1000"></textarea>
                        <p style="display: none" id="error_message">{{trans('app.error_message')}}</p>
                    </div>
                    <div>
                        <button class="send" type="submit">{{trans('app.send')}}</button>
                    </div>
                </form>
            </div>
            <div class="social-tabs">
                <a target="_blank" href="{{option('facebook_page')}}">Facebook</a>
                <a target="_blank" href="{{option('twitter_page')}}">Twitter</a>
                <a target="_blank" href="{{option('youtube_page')}}">Youtube</a>
            </div>
        </div>
    </section>
@endsection
@push('scripts')
    <script>

        $('#contact-form').submit(function (e) {
            arr = {
                'name': $('[name="first_name"]').val(),
                'last': $('[name="last_name"]').val(),
                'email': $('[name="email"]').val(),
                'number': $('[name="number"]').val(),
                'message': $('[name="message"]').val()
            };
            e.preventDefault();
            if(validate(arr)){
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: "post",
                    url: "{{route('contact-us')}}",
                    data: arr,
                    success: function () {
                        $('.contact-section').fadeOut(1000, function () {
                        $('.social-tabs').hide();
                        $('.confirm').show();
                        });
                    },
                    error:function () {
                        alert("Internal server error")
                    }
                })
            }
        });

        function validate(arr) {
            var valid = true;
            regex = /^\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i;
            name_regex =  /^[a-zA-Z\s]*$/;

            if(arr.name.length < 3 || arr.name.length > 50 || !name_regex.test(arr.name)){
                $('#error_first_name').show();
                valid = false;
            }else{
                $('#error_first_name').hide();
            }
            if(arr.last.length < 3 || arr.last.length > 50 || !name_regex.test(arr.last)){
                $('#error_last_name').show();
                valid = false;
            }else{
                $('#error_last_name').hide();
            }
            if(arr.number.length !== 11){
                $('#error_number').show();
                valid = false;
            }else{
                $('#error_number').hide();
            }
            if(!regex.test(arr.email)){
                $('#error_email').show();
                valid = false;
            }else{
                $('#error_email').hide();
            }
            if(arr.message.length < 3 || arr.message.length > 1000){
                $('#error_message').show();
                valid = false;
            }else{
                $('#error_message').hide();
            }
            return valid;
        }
    </script>
@endpush()

resources/views/index.blade.php
 @extends('layouts.app')
    @section('title',trans('app.home'))
    @section('content')
    <section class="home-section">
            @include('layouts.partials.header')
        <div class="container">
            <div class="social-h">
                <a  target="_blank" href="{{option('facebook_page')}}">Facebook</a>
                <a  target="_blank" href="{{option('twitter_page')}}">Twitter</a>
                <a  target="_blank" href="{{option('youtube_page')}}">Youtube</a>
            </div>
            <div class="scroll">
                <a href="#"><i class="icon-arrow-down"></i> انتقل للأسفل</a>
            </div>
            <div class="swiper">
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        @foreach($categories as $category)
                            <div class="swiper-slide">
                                <div class="image"><img src="{{thumbnail($category->cover->path,'home-slider')}}" alt=""></div>
                                <div class="text">
                                    <p class="title">{{$category->name}}</p>
                                    <p><span>{{category_count($category->id)}}.</span> {{trans('app.video')}}</p>
                                    <a href="{{$category->path}}" class="more">
                                        {{trans('app.view_more')}} <i class="icon-slider-left"></i>
                                    </a>
                                    <a href="{{$category->path}}" class="play">
                                        <i class="icon-play"></i>
                                    </a>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
                <div class="swiper-button-next swiper-button-white">
                    <i class="icon-slider-right"></i>
                </div>
                <div class="swiper-button-prev swiper-button-white">
                    <i class="icon-slider-left"></i>
                </div>
            </div>
        </div>
</section>
<section class="padding-section category-videos">

    <div class="container">
        <p class="title-section main-title-font  black-color ">{{trans('app.latest_videos')}}</p>
        <hr class="under-line">
        <div class="cards">
            @include('extensions.index-videos', $videos)
            @if(count($videos) == 12)
            <div class="btn-more">
                <button class="more">{{trans('app.more')}}</button>
            </div>
            @endif
        </div>

    </div>
</section>
    @include('extensions.subscribe')

<script>
    var swiper = new Swiper('.swiper .swiper-container', {
        slidesPerView: 3,
        spaceBetween: 0,
        centeredSlides: true,
        slideToClickedSlide: true,
        simulateTouch:false,
        loop: true,
        autoplay: true,
        navigation: {
            prevEl: '.swiper-button-next.swiper-button-white',
            nextEl: '.swiper-button-prev.swiper-button-white'
        },
        breakpoints: {
            768: {
                slidesPerView: 1,
                spaceBetween: 50
            }
        },

    });

    $(function () {
        offset = 12
        $('.btn-more').on('click', function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                type: "get",
                url: "{{route('index')}}",
                data: {'offset': offset, 'limit': 12},
                success: function (data) {
                    if (data.count > 0) {
                        $(data.view).insertBefore('.btn-more');
                        offset += data.count;
                        $('.card').each(function () {
                            if ($(this).isInViewport()) {
                                $(this).css({
                                    opacity: '1',
                                    transform: 'translateY(-10px)'
                                });
                            }
                        });
                    }
                    if (data.count < 12)
                        $('.btn-more').remove();
                }
            })
        });
    })

</script>
    @endsection

resources/views/page-details.blade.php
@extends('layouts.app')
@section('title',$page->slug)
@section('content')
    <section class="about original">
        @include('layouts.partials.header')
        <div class="container">
            <p class="third-title-font padding-section">{{$page->title}}</p>
            <div class="sub-icons">
                <img src="{{assets('assets')}}/images/tayer.png" alt="">
                <!--<img src="img/shapes.png" alt="" class="shapes">-->
            </div>
            <p>
                {{ strip_tags($page->content)}}
            </p>
            <div class="social-tabs">
                <a href="#">YOUTUBE</a>
                <a href="#">TWITTER</a>
                <a href="#">FACEBOOK</a>
            </div>
        </div>
    </section>
@endsection

resources/views/search.blade.php
@extends('layouts.app')
@section('title',trans('app.search').' | '.$q)
@section('content')
    <div class="search-section">
        <section>
            @include('layouts.partials.header')
                <div class="search-page">
                    <div class="container">
                        <form id="search">
                            <input type="text" name="q" maxlength="50" placeholder="إبحث" class="third-title-font">
                            <button name="search-submit">
                                <i class="icon-arrow-left"></i>
                            </button>
                        </form>
                        <img src="{{assets('assets')}}/images/red.png" alt="" class="red">
                    </div>
                </div>
                <div id="list">
                    <div class="container">
                        <img src="{{assets('assets')}}/images/green.png" alt="" class="green">
                        <div class="cards">
                            @include('extensions.index-videos', $videos)
                            <div id="more"></div>
                        </div>
                    </div>
                </div>
        </section>
        <div id="scroll-to"></div>
    </div>
@endsection
@push('scripts')
    <script>
        $('[name="search-submit"]').click(function (e) {
            e.preventDefault();
            let q = $('[name="q"]').val();
            window.location.href = encodeURI("{{route('index')}}" + '/search/' + encodeURIComponent(q));
        });

        offset = "{{$count}}";
        limit = 9;
        max = true
        $(window).scroll(function (e) {
            var hT = $('#scroll-to').offset().top,
                hH = $('#scroll-to').outerHeight(),
                wH = $(window).height(),
                wS = $(window).scrollTop();
            if (wS - 100 > (hT + hH - wH) && max) {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: "get",
                    url: "{{route('search',['q' => $q])}}",
                    data: {offset: offset, limit: limit},
                    async: false,
                    success: function (data) {
                        html = data.view;
                        if (data.count > 0) {
                            $(html).insertBefore('#more');
                            $('.card').each(function () {
                                if ($(this).isInViewport()) {
                                    $(this).css({
                                        opacity: '1',
                                        transform: 'translateY(-10px)'
                                    });
                                }
                            });
                            offset += data.count;
                        }
                        if (data.count < 9)
                            max = false;
                    }
                })
                return false;
            }
        })
    </script>
@endpush

resources/views/video-details.blade.php
@extends('layouts.app')
@section('meta')
    @include('extensions.meta',['post'=>$video])
@endsection
@section('title',$video->slug)
@section('content')

    <section class="video-section">
        @include('layouts.partials.header')
        <div class="container">
            <div class="video-wrapper">
                <div class="video-card" id="video">
                    <div class="video">
                        <video poster="{{thumbnail($video->image->path,'video-details')}}"
                               src="{{$video->media->path}}">
                        </video>
                    </div>
                    <button class="play-card"><i class="icon-play"></i></button>
                    <div class="over-video">
                        <div class="title d-inline-block">
                            <img src="{{thumbnail($category->image->path, 'category-logo')}}" alt="#">
                            <span class="second-title-font">{{$category->name}}</span>
                        </div>
                        <div class="hover-card  d-inline-block ">
                            <div class="social-icon" data-youtube="{{$video->media->path}}" data-url="{{$video->path}}"
                                 data-title="{!! $video->title !!}">
                                <a href="javascript:void(0)"><i class="icon-youtube youtube shareBtn"></i></a>
                                <a href="javascript:void(0)"><i class="icon-facebook facebook shareBtn"></i></a>
                                <a href="javascript:void(0)"><i class="icon-twitter twitter shareBtn"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="title-card clearfix">
                    <p class="second-title-font ">
                        {!! $video->title !!}
                    </p>
                </div>
            </div>

        </div>
    </section>
    <section class="padding-section video-details">
        <div class="container">
            <p class="title-section main-title-font  black-color ">{{trans('app.latest_videos')}}</p>
            <hr class="under-line">
            <div class="cards">
                @include('extensions.index-videos', $videos)
                @if(count($videos) == 6)
                    <div class="btn-more">
                        <button class="more">{{trans('app.more')}}</button>
                    </div>
                @endif
            </div>
        </div>
    </section>
    @include('extensions.subscribe')
@endsection
@push('scripts')
    <script src="https://www.youtube.com/iframe_api"></script>
    <script>
        $(function () {
            offset = 6
            $('.btn-more').on('click', function () {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: "get",
                    url: "{{route('posts.show',['slug'=> $video->slug])}}",
                    data: {'offset': offset, 'limit': 6},
                    success: function (data) {
                        if (data.count > 0) {
                            $(data.view).insertBefore('.btn-more');
                            offset += data.count;
                            $('.card').each(function () {
                                if ($(this).isInViewport()) {
                                    $(this).css({
                                        opacity: '1',
                                        transform: 'translateY(-10px)'
                                    });
                                }
                            });
                        }
                        if (data.count < 6)
                            $('.btn-more').remove();
                    }
                })
            });

            $(document).on('click','.play-card',function (e) {
                e.preventDefault()
                var video = $(this).closest('.video-card').find('video');
                var src = video[0].src;
                var div = $('#video');
                var height = div.height();
                var width = div.width();
                var vid = src.split('embed/')[1];

                player = new YT.Player('video', {
                    width: width,
                    height: height,
                    videoId: vid,
                    playerVars: { 'autoplay': 1, 'controls': 1 },
                    events:{
                        onStateChange: stopVideo
                    }
                });
            });
            function stopVideo(e) {
                if(e.data == 0)
                    $('.video-wrapper').html("<div class=\"video-card\" id=\"video\">\n" +
                        "                    <div class=\"video\">\n" +
                        "                        <video poster=\"{{thumbnail($video->image->path,'video-details')}}\"\n" +
                        "                               src=\"{{$video->media->path}}\">\n" +
                        "                        </video>\n" +
                        "                    </div>\n" +
                        "                    <button class=\"play-card\"><i class=\"icon-play\"></i></button>\n" +
                        "                    <div class=\"over-video\">\n" +
                        "                        <div class=\"title d-inline-block\">\n" +
                        "                            <img src=\"{{thumbnail($category->image->path, 'category-logo')}}\" alt=\"#\">\n" +
                        "                            <span class=\"second-title-font\">{{$category->name}}</span>\n" +
                        "                        </div>\n" +
                        "                        <div class=\"hover-card  d-inline-block \">\n" +
                        "                            <div class=\"social-icon\" data-youtube=\"{{$video->media->path}}\" data-url=\"{{$video->path}}\"\n" +
                        "                                 data-title=\"{!! $video->title !!}\">\n" +
                        "                                <a href=\"javascript:void(0)\"><i class=\"icon-youtube youtube shareBtn\"></i></a>\n" +
                        "                                <a href=\"javascript:void(0)\"><i class=\"icon-facebook facebook shareBtn\"></i></a>\n" +
                        "                                <a href=\"javascript:void(0)\"><i class=\"icon-twitter twitter shareBtn\"></i></a>\n" +
                        "                            </div>\n" +
                        "                        </div>\n" +
                        "                    </div>\n" +
                        "                </div>\n" +
                        "                <div class=\"title-card clearfix\">\n" +
                        "                    <p class=\"second-title-font \">\n" +
                        "                        {!! $video->title !!}\n" +
                        "                    </p>\n" +
                        "                </div>")
            }
        })
    </script>
@endpush